import { StyleSheet } from 'react-native';
import { colors } from './vars';
import { rf, rh, rw } from '../common/helpers/dimentions';

export const styles = StyleSheet.create({
  all: {
    alignItems: `center`,
    backgroundColor: `#333333`,
    borderRadius: 5,
    justifyContent: `center`,
    marginHorizontal: rh(1),
    width: rw(10),
  },
  alreadyAccount: {
    color: colors.black,
    fontSize: 14,
    fontWeight: '400',
    marginVertical: 4,
  },
  back: { alignItems: 'center', justifyContent: 'center' },
  children1: { justifyContent: 'space-between' },
  children2: { justifyContent: 'flex-start' },
  children3: { justifyContent: 'flex-end' },
  circle: { color: colors.white, fontSize: 20 },
  circles: {
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  container: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 0,
    width: '100%',
  },
  container1: { backgroundColor: colors.white, flex: 1 },
  continue: { fontSize: rf(1.5), textAlign: 'center' },
  cta: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 5,
    elevation: 5,
    justifyContent: 'center',
    marginVertical: 8,
    padding: 16,
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    width: '100%',
  },
  ctaskip: {
    alignItems: 'center',
    borderRadius: 5,
    elevation: 4,
    justifyContent: 'center',
    marginVertical: 16,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: `#000000`,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    width: '100%',
  },
  customerName: { flexDirection: 'row' },
  dataStyle: { marginTop: -3, paddingRight: rw(1) },
  download: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: rh(2),
  },
  getBizText: { color: colors.white },
  getBizView: { marginLeft: 16 },
  icon: { alignItems: `center`, flex: 1 },
  iconApp: { alignItems: 'center', marginVertical: rh(5) },
  inputshadow: {
    elevation: 8,
    shadowColor: `#000`,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
  },
  label: {
    color: colors.lightBlack,
    fontSize: rf(2.5),
    fontWeight: 500,
    marginLeft: rw(5),
    marginTop: rh(1),
    textAlign: `center`,
  },
  label1: {
    color: colors.lightBlack,
    fontSize: rf(1.75),
    // fontWeight: 500,
    textAlign: `center`,
    width: rw(85),
    // marginTop: rh(1),
  },
  label2: {
    color: colors.lightBlack,
    fontSize: rf(1.7),
    // fontWeight: 500,
    textAlign: `center`,
    width: rw(88.1),
    // marginTop: rh(1),
  },
  lastsday: {
    alignItems: `center`,
    backgroundColor: `#333333`,
    borderRadius: 5,
    justifyContent: `center`,
    marginHorizontal: rh(1),
    width: rw(17),
  },
  linktext: {
    color: `#0000FF`,
  },
  loginStyle: {
    color: colors.black,
    fontSize: 14,
    fontWeight: '400',
    marginVertical: 4,
  },
  nextButton: { position: 'absolute' },
  nextButtonStyle: { alignItems: 'flex-end', width: rw(75) },
  noStyle: {
    alignItems: `center`,
    borderColor: colors.primary,
    borderRadius: 5,
    borderWidth: 1,
    flex: 1,
    paddingVertical: rh(0.7),
  },
  numberDisabled: {
    borderColor: colors.grey,
    borderRightWidth: 1,
    color: colors.grey,
    marginRight: rw(5),
    paddingLeft: rw(1),
    paddingRight: rw(5),
  },
  numberEnabled: {
    borderColor: colors.black,
    borderRightWidth: 1,
    color: colors.grey,
    marginRight: rw(5),
    paddingLeft: rw(1),
    paddingRight: rw(5),
  },
  onboarding: { flex: 3 },
  onboardingTitle: {
    color: colors.black,
    fontSize: rf(3),
    fontWeight: '700',
  },
  onboardingTitle1: {
    color: colors.black,
    fontSize: rf(3),
    fontWeight: '700',
  },
  oneNumber: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: rh(8),
  },
  otpContainer: { flexDirection: 'row', justifyContent: 'space-between' },
  otpContainerText: {
    paddingBottom: 4,
    paddingTop: 4,
    textAlign: 'center',
  },
  otpStyle: {
    borderRadius: 5,
    marginHorizontal: 4,
    textAlign: 'center',
    width: 45,
  },
  paginatorSkip: { flexDirection: 'column' },
  paginators: { flexDirection: 'row', height: 32, paddingLeft: 16 },
  phoneNumber: {
    marginBottom: rh(2.5),
    paddingHorizontal: rw(0.5),
    width: '100%',
  },
  profile: { alignItems: `flex-end`, flex: 1 },
  redirectText: { fontSize: 20, textAlign: 'center' },
  redirectView: { alignItems: 'center', justifyContent: 'center' },
  routeHead: { elevation: 5 },
  skipContainer: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    marginVertical: rh(4),
  },
  skipView: { paddingLeft: 20 },
  skipView1: {
    height: 20,
  },
  skipimgbg: {
    margin: 0,
    padding: 0,
    width: rw(85),
  },
  skipscrnbtn: { marginTop: 0 },
  skipscrnlrprt: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  subTitle: {
    color: colors.black,
    fontSize: rf(2.2),
    fontWeight: '400',
  },
  subTitle1: {
    color: colors.black,
    fontSize: rf(2.2),
    fontWeight: '400',
  },
  subTitle2: {
    color: colors.black,
    fontSize: rf(2.2),
    fontWeight: '400',
    marginBottom: rh(2),
  },
  title: { flex: 1 },
  title1: {
    alignItems: `center`,
    backgroundColor: colors.white,
    borderRadius: 25,
    flexDirection: `row`,
    justifyContent: `space-between`,
    paddingLeft: 4,
    paddingRight: 6,
    paddingVertical: 3,
    position: `absolute`,
    top: rh(-1.75),
    width: rw(20),
  },
  titleRight: { alignItems: `flex-end`, flex: 1 },
  titleRight1: {
    alignItems: `center`,
    backgroundColor: colors.white,
    borderRadius: 25,
    flexDirection: `row`,
    justifyContent: `space-between`,
    paddingLeft: 6,
    paddingRight: 4,
    paddingVertical: 3,
    position: `absolute`,
    top: rh(-1.75),
    width: rw(20),
  },
  today: {
    alignItems: `center`,
    backgroundColor: `white`,
    borderColor: colors.grey,
    borderRadius: 5,
    borderWidth: 1,
    justifyContent: `center`,
    marginHorizontal: rh(1),
    width: rw(20),
  },
  toogleButton: { width: '100%' },
  verifyafter: {
    borderBottomColor: colors.primary,
    borderBottomWidth: 2,
    fontSize: rf(4),
    fontWeight: '400',
    marginHorizontal: 16,
    padding: 8,
    textAlign: 'center',
    width: '20%',
  },
  verifybefore: {
    borderBottomColor: colors.secondary,
    borderBottomWidth: 2,
    fontSize: rf(4),
    fontWeight: '400',
    marginHorizontal: rh(2),
    padding: 8,
    textAlign: 'center',
    width: rw(16),
  },
  waapUrlStyle: {
    color: colors.primary,
    fontSize: 18,
    textAlign: 'center',
  },
  welcomeText: {
    color: colors.secondary,
    fontSize: rf(3),
    fontWeight: '700',
  },
  welcomeView: { alignItems: 'center' },
  yDay: {
    alignItems: `center`,
    backgroundColor: `white`,
    borderColor: colors.grey,
    borderRadius: 5,
    borderWidth: 1,
    justifyContent: `center`,
    marginHorizontal: rh(1),
    width: rw(17),
  },
  yesStyle: {
    alignItems: `center`,
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    borderRadius: 5,
    borderWidth: 1,
    flex: 1,
    marginLeft: rw(5),
    paddingVertical: rh(0.7),
  },
});
